arm_position_controller:
  panda_gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - panda_finger_joint1
    gains: 
      panda_finger_joint1: {p: 10.0, i: 0.01, d: 1.0}