arm_position_controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  panda_joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint1
    pid: {p: 1.0, i: 0.01, d: 0.05}

  panda_joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint2
    pid: {p: 1.0, i: 0.01, d: 0.05}

  panda_joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint3
    pid: {p: 1.0, i: 0.01, d: 0.05}
  
  panda_joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint4
    pid: {p: 1.0, i: 0.01, d: 0.05}
  
  panda_joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint5
    pid: {p: 1.0, i: 0.01, d: 0.05}

  panda_joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint6
    pid: {p: 1.0, i: 0.01, d: 0.05}

  panda_joint7_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint7
    pid: {p: 1.0, i: 0.01, d: 0.05}

  # gripper_controller:
  #   type: position_controllers/JointPositionController
  #   joints: 
  #     - panda_finger_joint1
  #     - panda_finger_joint2
  #   pid:
  #     p: 1.0
  #     i: 0.01
  #     d: 0.05

  # gripper_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: 
  #     - panda_finger_joint1
  #     - panda_finger_joint2
  #   pid:
  #     p: 1.0
  #     i: 0.01
  #     d: 0.05
