/arm_position_controller/gazebo_ros_control:

  # panda_joint1_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: panda_joint1
  #   pid: {p: 100, i: 1.0, d: 0.0}

  pid_gains:
    panda_joint1: { p: 1, i: 1.0, d: 1.0 }

    panda_joint2: { p: 10, i: 1.0, d: 1.0 }

    panda_joint3: { p: 10, i: 1.0, d: 1.0 }

    panda_joint4: { p: 10, i: 1.0, d: 1.0 }

    panda_joint5: { p: 10, i: 1.0, d: 1.0 }

    panda_joint6: { p: 10, i: 1.0, d: 1.0 }

    panda_joint7: { p: 10, i: 1.0, d: 1.0 }

    panda_finger_joint1: { p: 10, i: 1.0, d: 1.0 }

    panda_finger_joint2: { p: 10, i: 1.0, d: 1.0 }

